### ISSUE TITLE
label options aren't used in viz.line

### ISSUE THREAD

**Issue by hawkrobe** [probmods/webppl-viz#57]
The readme specifies that you can pass an options argument specifying `xLabel` and `yLabel` to `viz.line`, e.g.:

```
viz.line([1,2,3], [4,5,6], {xLabel: 'foo', yLabel: 'bar'})
```

but it doesn't look like these options are used anywhere in the definition of `viz.line` the way they are for `viz.hist` or `viz.bar`:

https://github.com/probmods/webppl-viz/blob/bd7fbae346b9deaac52298aa1b541e6ecf4a068b/src/index.js#L1352-L1359

**Comment by longouyang** [comment]
Fixed in 4819a2df240b924aee32987c8df827bc30ec4182

(and I just updated the version that probmods2 points to, so it should be available there)

FYI, big changes are coming to viz this and next week; it'll look a lot more like `Infer` -- a single command, `viz`, that takes an optional specification of the visualization to show.

**Comment by longouyang** [comment]
Update: I tried to do the big viz overhaul but smaller bug fixes got in the way. This'll probably be a longer term project.

**Comment by hawkrobe** [comment]
thanks for the update -- sounds like a totally reasonable timeline :)
